[package]
name = "tree-surgeon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
ariadne = "0.1.5"
chumsky = "0.8.0"
clap = { version = "3.2.2", features = ["derive"] }
miette = { version = "4.7.1", features = ["fancy"] }
thiserror = "1.0.31"
tree-sitter = "0.20.6"

[build-dependencies]
cc = "*"
